# Generated by Django 4.0.5 on 2022-06-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=45, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cestas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fcreacion', models.DateTimeField(blank=True, db_column='Fcreacion', null=True)),
                ('fultimo', models.DateTimeField(blank=True, db_column='Fultimo', null=True)),
            ],
            options={
                'db_table': 'cestas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('apellidos', models.CharField(blank=True, db_column='Apellidos', max_length=150, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('nif', models.CharField(blank=True, db_column='NIF', max_length=9, null=True)),
                ('cuenta', models.CharField(blank=True, db_column='Cuenta', max_length=24, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('name_usuario', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'colores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, db_column='Calle', max_length=145, null=True)),
                ('localidad', models.CharField(blank=True, db_column='Localidad', max_length=45, null=True)),
                ('cporta', models.IntegerField(blank=True, db_column='CPorta', null=True)),
                ('provincia', models.CharField(blank=True, db_column='Provincia', max_length=45, null=True)),
                ('pais', models.CharField(blank=True, db_column='Pais', max_length=45, null=True)),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disenos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disenos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=50, null=True)),
            ],
            options={
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'imagenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('iva', models.DecimalField(blank=True, db_column='IVA', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'iva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=2500, null=True)),
            ],
            options={
                'db_table': 'mensajes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=45, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coste', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('descuento', models.DecimalField(blank=True, db_column='Descuento', decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('finicio', models.DateTimeField(blank=True, db_column='Finicio', null=True)),
                ('ffin', models.DateTimeField(blank=True, db_column='Ffin', null=True)),
                ('url_imagen', models.CharField(blank=True, db_column='URL_imagen', max_length=250, null=True)),
            ],
            options={
                'db_table': 'promociones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('talla', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tallas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocategoria',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipocategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipomensaje',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipomensaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=45)),
                ('contrasena', models.CharField(max_length=50)),
                ('tipousuario', models.IntegerField(db_column='tipoUsuario')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valoraciones',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('valoracion', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'valoraciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientecategoria',
            fields=[
                ('idcliente', models.OneToOneField(db_column='idCliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.clientes')),
            ],
            options={
                'db_table': 'clientecategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clienteimagen',
            fields=[
                ('idcliente', models.OneToOneField(db_column='idCliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.clientes')),
            ],
            options={
                'db_table': 'clienteimagen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disenocategoria',
            fields=[
                ('iddiseno', models.OneToOneField(db_column='idDiseno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.disenos')),
            ],
            options={
                'db_table': 'disenocategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disenocolor',
            fields=[
                ('iddiseno', models.OneToOneField(db_column='idDiseno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.disenos')),
            ],
            options={
                'db_table': 'disenocolor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disenoimagen',
            fields=[
                ('iddiseno', models.OneToOneField(db_column='idDiseno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.disenos')),
            ],
            options={
                'db_table': 'disenoimagen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disenotalla',
            fields=[
                ('iddiseno', models.OneToOneField(db_column='idDiseno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.disenos')),
            ],
            options={
                'db_table': 'disenotalla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disenovalora',
            fields=[
                ('iddiseno', models.OneToOneField(db_column='idDiseno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.disenos')),
            ],
            options={
                'db_table': 'disenovalora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gustodiseno',
            fields=[
                ('iddiseno', models.OneToOneField(db_column='idDiseno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.disenos')),
                ('gusta', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gustodiseno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lineacesta',
            fields=[
                ('idproducto', models.OneToOneField(db_column='idProducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.productos')),
                ('preciounitario', models.DecimalField(blank=True, db_column='PrecioUnitario', decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('total', models.DecimalField(blank=True, db_column='Total', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'lineacesta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productocategoria',
            fields=[
                ('idcategoria', models.OneToOneField(db_column='idCategoria', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.categorias')),
            ],
            options={
                'db_table': 'productocategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productocolor',
            fields=[
                ('idproducto', models.OneToOneField(db_column='idProducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.productos')),
            ],
            options={
                'db_table': 'productocolor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productoimagen',
            fields=[
                ('idproducto', models.OneToOneField(db_column='idProducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.productos')),
            ],
            options={
                'db_table': 'productoimagen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productotalla',
            fields=[
                ('idproducto', models.OneToOneField(db_column='idProducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.productos')),
            ],
            options={
                'db_table': 'productotalla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productovalora',
            fields=[
                ('idproducto', models.OneToOneField(db_column='idProducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.productos')),
            ],
            options={
                'db_table': 'productovalora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salausuario',
            fields=[
                ('idsala', models.OneToOneField(db_column='idSala', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.salas')),
            ],
            options={
                'db_table': 'salausuario',
                'managed': False,
            },
        ),
    ]
