# Generated by Django 4.0.5 on 2022-06-15 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_categorias_options_alter_cestas_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disenosexo',
            fields=[
                ('iddiseno', models.OneToOneField(db_column='idDiseno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.disenos')),
            ],
            options={
                'db_table': 'disenosexo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productosexo',
            fields=[
                ('idproducto', models.OneToOneField(db_column='idProducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.productos')),
            ],
            options={
                'db_table': 'productosexo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sexos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sexos',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cestas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clientecategoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clienteimagen',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='colores',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='direcciones',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disenocategoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disenocolor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disenoimagen',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disenos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disenotalla',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disenovalora',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estados',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gustodiseno',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='imagenes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='iva',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lineacesta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mensajes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productocategoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productocolor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productoimagen',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productotalla',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productovalora',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='promociones',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='salas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='salausuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tallas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipocategoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipomensaje',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='valoraciones',
            options={'managed': False},
        ),
    ]
